# Generated by Django 4.2.27 on 2026-01-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(max_length=200, verbose_name='试卷标题')),
                ('description', models.TextField(blank=True, verbose_name='试卷描述')),
                ('total_score', models.DecimalField(decimal_places=1, default=100, max_digits=6, verbose_name='总分')),
                ('pass_score', models.DecimalField(decimal_places=1, default=60, max_digits=6, verbose_name='及格分')),
                ('time_limit', models.PositiveIntegerField(default=120, verbose_name='时间限制(分钟)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('is_random_question', models.BooleanField(default=False, verbose_name='是否随机题目顺序')),
                ('is_random_option', models.BooleanField(default=False, verbose_name='是否随机选项顺序')),
                ('show_answer_after_submit', models.BooleanField(default=True, verbose_name='提交后显示答案')),
                ('allow_review', models.BooleanField(default=True, verbose_name='允许查看解析')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='tags.category', verbose_name='分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('title', models.CharField(help_text='如：一、选择题', max_length=200, verbose_name='大题标题')),
                ('description', models.TextField(blank=True, help_text='如：每题2分，共20分', verbose_name='说明')),
                ('question_type', models.CharField(blank=True, help_text='限制此大题只能添加特定类型的题目', max_length=20, verbose_name='题目类型')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='papers.paper', verbose_name='所属试卷')),
            ],
            options={
                'verbose_name': '试卷大题',
                'verbose_name_plural': '试卷大题',
                'db_table': 'paper_sections',
                'ordering': ['paper', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('score', models.DecimalField(decimal_places=1, default=5, max_digits=5, verbose_name='分值')),
                ('question_number', models.PositiveSmallIntegerField(default=1, verbose_name='题号')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='papers.paper', verbose_name='所属试卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='questions.question', verbose_name='题目')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_questions', to='papers.papersection', verbose_name='所属大题')),
            ],
            options={
                'verbose_name': '试卷题目',
                'verbose_name_plural': '试卷题目',
                'db_table': 'paper_questions',
                'ordering': ['paper', 'section', 'order', 'question_number'],
                'unique_together': {('paper', 'question')},
            },
        ),
    ]
