# Generated by Django 4.2.27 on 2026-01-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('title', models.TextField(verbose_name='题目标题')),
                ('type', models.CharField(choices=[('single', '单选题'), ('multi', '多选题'), ('judge', '判断题'), ('blank', '填空题'), ('short', '简答题'), ('programming', '编程题')], db_index=True, default='single', max_length=20, verbose_name='题目类型')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], db_index=True, default=2, verbose_name='难度')),
                ('score', models.DecimalField(decimal_places=1, default=5, max_digits=5, verbose_name='默认分值')),
                ('content', models.TextField(blank=True, help_text='支持 Markdown', verbose_name='题目内容')),
                ('answer', models.TextField(blank=True, help_text='选择题存选项ID，填空题存答案，编程题存测试用例', verbose_name='标准答案')),
                ('answer_analysis', models.TextField(blank=True, verbose_name='答案解析')),
                ('programming_language', models.CharField(blank=True, max_length=50, verbose_name='编程语言')),
                ('time_limit', models.PositiveIntegerField(blank=True, default=1000, verbose_name='时间限制(ms)')),
                ('memory_limit', models.PositiveIntegerField(blank=True, default=256, verbose_name='内存限制(MB)')),
                ('test_cases', models.JSONField(blank=True, default=list, verbose_name='测试用例')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='正确次数')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='tags.category', verbose_name='分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('label', models.CharField(default='A', help_text='如 A, B, C, D', max_length=10, verbose_name='选项标识')),
                ('content', models.TextField(verbose_name='选项内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '题目选项',
                'verbose_name_plural': '题目选项',
                'db_table': 'question_options',
                'ordering': ['question', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='文件')),
                ('type', models.CharField(choices=[('image', '图片'), ('audio', '音频'), ('video', '视频'), ('document', '文档'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='questions.question', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '题目附件',
                'verbose_name_plural': '题目附件',
                'db_table': 'question_attachments',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type', 'difficulty'], name='questions_type_14d64e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_public', 'is_deleted'], name='questions_is_publ_3f5aeb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'label')},
        ),
    ]
