# Generated by Django 4.2.27 on 2026-01-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(max_length=200, verbose_name='考试名称')),
                ('description', models.TextField(blank=True, verbose_name='考试说明')),
                ('type', models.CharField(choices=[('exam', '正式考试'), ('practice', '练习模式'), ('mock', '模拟考试')], default='exam', max_length=20, verbose_name='考试类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('not_started', '未开始'), ('in_progress', '进行中'), ('ended', '已结束'), ('grading', '阅卷中'), ('finished', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='覆盖试卷时长', null=True, verbose_name='考试时长(分钟)')),
                ('max_attempts', models.PositiveSmallIntegerField(default=1, verbose_name='最大尝试次数')),
                ('allow_late_submit', models.BooleanField(default=False, verbose_name='允许迟交')),
                ('late_submit_minutes', models.PositiveIntegerField(default=0, verbose_name='迟交时限(分钟)')),
                ('anti_cheat_enabled', models.BooleanField(default=False, verbose_name='启用防作弊')),
                ('fullscreen_required', models.BooleanField(default=False, verbose_name='强制全屏')),
                ('switch_limit', models.PositiveSmallIntegerField(default=0, verbose_name='切屏次数限制')),
                ('auto_publish_score', models.BooleanField(default=True, verbose_name='自动发布成绩')),
                ('score_publish_time', models.DateTimeField(blank=True, null=True, verbose_name='成绩发布时间')),
                ('is_public', models.BooleanField(default=False, help_text='公开考试所有人可参加', verbose_name='是否公开')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_exams', to=settings.AUTH_USER_MODEL, verbose_name='允许参加的用户')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='papers.paper', verbose_name='关联试卷')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'exams',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('submitted', '已提交'), ('timeout', '超时'), ('grading', '阅卷中'), ('finished', '已完成')], default='not_started', max_length=20, verbose_name='状态')),
                ('attempt', models.PositiveSmallIntegerField(default=1, verbose_name='尝试次数')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始答题时间')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='得分')),
                ('objective_score', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='客观题得分')),
                ('subjective_score', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='主观题得分')),
                ('switch_count', models.PositiveSmallIntegerField(default=0, verbose_name='切屏次数')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='浏览器信息')),
                ('question_order', models.JSONField(blank=True, default=list, verbose_name='题目顺序')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='exams.exam', verbose_name='考试')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'db_table': 'exam_records',
                'ordering': ['-created_at'],
                'unique_together': {('exam', 'user', 'attempt')},
            },
        ),
    ]
