# Generated by Django 4.2.27 on 2026-01-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('answer_content', models.TextField(blank=True, help_text='选择题存选项ID，其他题存文本', verbose_name='作答内容')),
                ('answer_files', models.JSONField(blank=True, default=list, help_text='编程题代码文件等', verbose_name='作答附件')),
                ('status', models.CharField(choices=[('not_answered', '未作答'), ('answered', '已作答'), ('marked', '已标记'), ('graded', '已批改')], default='not_answered', max_length=20, verbose_name='状态')),
                ('is_marked', models.BooleanField(default=False, verbose_name='是否标记')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='得分')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('comment', models.TextField(blank=True, verbose_name='批改评语')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='批改时间')),
                ('first_answer_time', models.DateTimeField(blank=True, null=True, verbose_name='首次作答时间')),
                ('last_answer_time', models.DateTimeField(blank=True, null=True, verbose_name='最后作答时间')),
                ('answer_duration', models.PositiveIntegerField(default=0, verbose_name='作答时长(秒)')),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examrecord', verbose_name='考试记录')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL, verbose_name='批改人')),
                ('paper_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='papers.paperquestion', verbose_name='试卷题目')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'db_table': 'answers',
                'ordering': ['exam_record', 'paper_question__question_number'],
                'unique_together': {('exam_record', 'paper_question')},
            },
        ),
    ]
