# Generated by Django 4.2.27 on 2026-01-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam_count', models.PositiveIntegerField(default=0, verbose_name='参加考试次数')),
                ('passed_count', models.PositiveIntegerField(default=0, verbose_name='及格次数')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总得分')),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='平均分')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='答题数')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='正确数')),
                ('accuracy_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='正确率')),
                ('total_duration', models.PositiveIntegerField(default=0, verbose_name='总学习时长(秒)')),
                ('weak_tags', models.JSONField(blank=True, default=list, verbose_name='弱项标签')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_statistics', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户统计',
                'verbose_name_plural': '用户统计',
                'db_table': 'user_statistics',
            },
        ),
        migrations.CreateModel(
            name='ExamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('participant_count', models.PositiveIntegerField(default=0, verbose_name='参与人数')),
                ('submitted_count', models.PositiveIntegerField(default=0, verbose_name='提交人数')),
                ('graded_count', models.PositiveIntegerField(default=0, verbose_name='已批改人数')),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='平均分')),
                ('highest_score', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='最高分')),
                ('lowest_score', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='最低分')),
                ('median_score', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='中位数')),
                ('pass_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='及格率')),
                ('score_distribution', models.JSONField(blank=True, default=dict, verbose_name='分数分布')),
                ('question_stats', models.JSONField(blank=True, default=dict, verbose_name='题目统计')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='exams.exam', verbose_name='考试')),
            ],
            options={
                'verbose_name': '考试统计',
                'verbose_name_plural': '考试统计',
                'db_table': 'exam_statistics',
            },
        ),
    ]
