# Generated by Django 4.2.27 on 2026-01-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('pending', '待分配'), ('in_progress', '进行中'), ('completed', '已完成'), ('reviewed', '已复核')], default='pending', max_length=20, verbose_name='状态')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总数')),
                ('graded_count', models.PositiveIntegerField(default=0, verbose_name='已批改数')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_tasks', to='exams.exam', verbose_name='考试')),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_tasks', to=settings.AUTH_USER_MODEL, verbose_name='阅卷人')),
                ('question', models.ForeignKey(blank=True, help_text='如果指定，只批改该题目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_tasks', to='questions.question', verbose_name='指定题目')),
            ],
            options={
                'verbose_name': '阅卷任务',
                'verbose_name_plural': '阅卷任务',
                'db_table': 'grading_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
